YAML
name: Save Traffic
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  traffic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Collect traffic
        uses: sangonzal/repository-traffic-action@v0.1.6
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path_traffic: traffic
      - name: Commit files
        run: |
          git config --local user.email "bot@github.com"
          git config --local user.name "Traffic Bot"
          git add traffic/
          git diff --staged --quiet || git commit -m "Update traffic data"
          git push
